// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TravelCompanion.Domain.Models;

public partial class AppUser
{
    public int AppUserId { get; set; }

    public Guid AppUserGuid { get; set; }

    public string Email { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<Trip> Trips { get; set; } = new List<Trip>();
}