// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TravelCompanion.Domain.Models;

public partial class Companion
{
    public int CompanionId { get; set; }

    public Guid CompanionGuid { get; set; }

    public int TripId { get; set; }

    public string Name { get; set; }

    public string CompanionNotes { get; set; }

    public virtual Trip Trip { get; set; }
}