// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TravelCompanion.Domain.Models;

public partial class Trip
{
    public int TripId { get; set; }

    public Guid TripGuid { get; set; }

    public int AppUserId { get; set; }

    public string LodgingName { get; set; }

    public string LodgingAddress { get; set; }

    public string LodgingCity { get; set; }

    public string LodgingState { get; set; }

    public string LodgingCountry { get; set; }

    public string LodgingPostalCode { get; set; }

    public DateTime? ArrivalDate { get; set; }

    public DateTime? DepartureDate { get; set; }

    public string TripNotes { get; set; }

    public virtual AppUser AppUser { get; set; }

    public virtual ICollection<Companion> Companions { get; set; } = new List<Companion>();

    public virtual ICollection<TripChat> TripChats { get; set; } = new List<TripChat>();

    public virtual ICollection<TripEvent> TripEvents { get; set; } = new List<TripEvent>();
}