// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TravelCompanion.Domain.Models;

public partial class TripEvent
{
    public int TripEventId { get; set; }

    public Guid TripEventGuid { get; set; }

    public int TripId { get; set; }

    public string EventName { get; set; }

    public string VenueName { get; set; }

    public string VenueAddress { get; set; }

    public string VenueCity { get; set; }

    public string VenueState { get; set; }

    public string VenueCountry { get; set; }

    public string VenuePostalCode { get; set; }

    public DateTime? StartDateTime { get; set; }

    public DateTime? EndDateTime { get; set; }

    public string EventNotes { get; set; }

    public virtual Trip Trip { get; set; }
}