// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TravelCompanion.Domain.Models;

public partial class TripChat
{
    public int TripChatId { get; set; }

    public Guid TripChatGuid { get; set; }

    public int TripId { get; set; }

    public string Description { get; set; }

    public string Chat { get; set; }

    public virtual Trip Trip { get; set; }
}