CREATE TABLE [dbo].[AppUser]
(
	[AppUserId] INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
	[AppUserGuid] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
	[Email] NVARCHAR(256) NOT NULL CONSTRAINT UNQ_AppUser_Email UNIQUE,
	[FirstName] NVARCHAR(100) NOT NULL,
	[LastName] NVARCHAR(100) NOT NULL,
	[IsActive] BIT NOT NULL DEFAULT 1,
)
