CREATE TABLE [dbo].[TripChat]
(
	[TripChatId] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[TripChatGuid] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
	TripId INT NOT NULL FOREIGN KEY REFERENCES Trip(TripId),
	[Description] NVARCHAR(100) NULL,
	Chat NVARCHAR(MAX) NULL,
)
