CREATE TABLE [dbo].[TripEvent]
(
	[TripEventId] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[TripEventGuid] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
	TripId INT NOT NULL FOREIGN KEY REFERENCES Trip(TripId),
	EventName NVARCHAR(100) NULL,
	VenueName NVARCHAR(100) NULL,
	VenueAddress NVARCHAR(100) NULL,
	VenueCity NVARCHAR(100) NULL,
	VenueState NVARCHAR(100) NULL,
	VenueCountry NVARCHAR(100) NULL,
	VenuePostalCode NVARCHAR(100) NULL,
	StartDateTime DATETIME NULL,
	EndDateTime DATETIME NULL,
	EventNotes NVARCHAR(MAX) NULL
)
