// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TravelCompanion.Domain.DTOs;

public class TripChatInfoDto
{
    public int TripChatId { get; set; }

    public Guid TripChatGuid { get; set; }

    public int TripId { get; set; }

    public string Description { get; set; }
}