// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TravelCompanion.Domain.DTOs;

public class TripChatDto : TripChatInfoDto
{
    public string Chat { get; set; }
}